let dados = [
    {titulo: "Agradecimentos",
     descricao: "Agradeço minha filha pela idéia. <p> Obrigado Rafaella, Guilerme e Luciano por serem ótimos professores e a Alura e o Gemini por essa oportunidade incrivel, onde eu que não tinha experiencia nenhuma em HTML, JavaScript e CSS, pude criar meu primeiro projeto.",
     tags: "1",

    },

    {titulo: "Beuforroxo",
     descricao: "Rayle, Moon, Cristian e Paulo Jr. mergulhavam de cabeça em aventuras alucinantes, desafiando limites e quebrando regras a cada esquina no bairro Beuforroxo. Com Rayle no volante de um foguete caseiro, Moon tentando domesticar um dragão de estimação 'seu chihuahua' , Cristian tentando decifrar hieróglifos em um pacote de batata frita e Paulo Jr. convencido de que é um ninja 'correndo com as mãos para trás'  as aventuras nunca faltavam. Escondido dos olhares indiscretos, o terreno baldio era o palco de suas mais excêntricas criações. Ali, entre sucata e peças aleatórias, eles forjavam planos que prometiam revolucionar o mundo... ou pelo menos a vizinhança.",
     tags: "2"},

     {titulo: "Ao infinito e jabuticabas",
      descricao:"Rayle, com seu olhar brilhante e um sorriso de orelha a orelha, anunciou o plano mais ambicioso de todos, construir um foguete para explorar o quintal do vizinho, o Sr. Silva, que tinha um pé de jabuticaba gigantesco. Mas havia um pequeno problema, faltavam algumas peças cruciais. Eles precisavam de um motor a jato feito de fogos de artifício, um tanque de combustível de refrigerante e um paraquedas feito de lençois velhos, Rayle explicando seu diagrama maluco desenhado em um guardanapo.Moon, com seu chihuahua, Rocket, no colo, sugeriu que poderia pegar o ventilador do quarto dela como turbina e a mangueira do jardim como tubo de escape. Cristian, com os olhos brilhando por trás de seus óculos devendava hieróglifos da batata frita tentando desvendar fórmula secreta para um combustível superpotente, enquanto Paulo Jr providênciava um carrinho de mercado do barateiro que se encontrava no bairro vizinho. Cristian, com um brilho nos olhos, anunciou ter decifrado o código secreto da batata frita: <p>_A combinação perfeita de carboidratos, sódio, gorduras e açúcar é a fórmula secreta de um supercombustível! e se misturarmos com um bom suco de tamarindo, teremos energia suficiente para lançar um foguete até a lua... ou pelo menos até o telhado da casa do Sr. Silva! <p> No outro bairro, lá estava Paulo Jr. entre os corredores do mercado, Paulo Jr. se movia como uma sombra, deslizando entre os carrinhos como se fosse um ninja em uma missão secreta, em um dos corredores ele pega um pacote de farinha, os olhares curiosos se voltavam para Paulo Jr. enquanto ele executava poses extravagantes, como se estivesse prestes a desferir um golpe mortal em um inimigo invisível, com um movimento rápido e preciso, Paulo Jr. lançou um punhado de farinha que se espalhou como uma nuvem branca, criando uma cortina de fumaça improvisada, Com um sorriso vitorioso agarrou o carrinho e saiu disparado em direção à saída, deixando para trás uma trilha de farinha e risadas. <p>Ao ser alcançado por um dos guardas, que ainda não havia se recuperado do ataque de risos disse: <p>_Parabéns, garoto! Você acaba de ganhar o prêmio de melhor ninja amador do mercado! Pode levar o carrinho... mas a farinha, você paga!",
      tags: "3"},
    
     ]
